services:
  # This service is for PyCharm and direct shell access.
  # It starts an idle container that waits for commands.
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: tda-geo:latest
    container_name: tda-geo-dev
    working_dir: /workspace
    # This command keeps the container running indefinitely without starting a server.
    command: tail -f /dev/null
    volumes:
      - .:/workspace
      - conda_store:/opt/conda
    ports:
      # Expose the port so PyCharm's auto-started server is accessible.
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # This service is for standalone, command-line use.
  # It directly starts a Jupyter Lab server.
  jupyter:
    image: tda-geo:latest # Uses the SAME image as the 'dev' service
    container_name: tda-geo-jupyter
    working_dir: /workspace
    command: >
      bash -c "
      micromamba run -n app python -m jupyter lab
      --ip=0.0.0.0 --port=8888 --allow-root --no-browser
      --NotebookApp.token='' --NotebookApp.password=''
      "
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  conda_store: